### ISSUE TITLE
事务的性能问题？

### ISSUE THREAD

**Issue by yeziuku** [milimoe/FunGame-Server#13]
因#12中添加了查询事务，但是是每一次查询都会创建事务，如果频繁Execute是否会影响性能？如果修改在Model中自行调用事务，又会提高代码量。

**Comment by milimoe** [comment]
目前应该不需要担心这个

**Comment by yeziuku** [comment]
重启此问题，建议在SQLHelper的事务不为null时，需要开发者自己提交或回滚更改。
提供一个Create方法用于创建事务。

**Comment by ChrisWynyard** [comment]
Done
